version: '3'
services:
  web:
    build:
      context: .
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/sample_app
      - public-data:/sample_app/public
      - tmp-data:/sample_app/tmp
      - log-data:/sample_app/log
    tty: true
    stdin_open: true
    environment:
      RAILS_ENV: production
  nginx:
    build:
      context: containers/nginx
    volumes:
      - public-data:/sample_app/public
      - tmp-data:/sample_app/tmp
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  public-data:
  tmp-data:
  log-data: