version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    command: redis-server --appendonly yes
  web: &web
    build:
      context: .
      dockerfile: Dockerfile_dev
    command: ./bin/rails s -b 0
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_URL: redis://redis:6379
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
    volumes:
      - .:/sample_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  webpacker:
    <<: *web
    command: ./bin/webpack-dev-server
    depends_on:
      - web
    ports:
      - "3035:3035"
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none

volumes:
  bundle-data:
  redis:
