version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./tmp/db:/var/lib/mysql
  web: &web
    build: .
    command: ./bin/rails s -b 0
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
    volumes:
      - .:/sample_app
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true
    stdin_open: true
  webpacker:
    <<: *web
    command: ./bin/webpack-dev-server
    depends_on:
      - web
    ports:
      - "3035:3035"

volumes:
  bundle-data:
